# Generated by Django 5.2.17 on 2026-09-24 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCNPJ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9]{14}\\Z', 'Informe os 14 números do CNPJ, sem máscara.')])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'histórico de CNPJ',
                'verbose_name_plural': 'históricos de CNPJ',
                'db_table': 'historico_cnpj',
                'ordering': ['-data_inicio', '-id'],
                'managed': False,
            },
        ),
    ]
