# Generated by Django 5.2.17 on 2026-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cnpj_obrigatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='função')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='e-mail')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco enquanto o contato estiver vigente.', null=True, verbose_name='data de encerramento')),
            ],
            options={
                'verbose_name': 'contato do condomínio',
                'verbose_name_plural': 'contatos dos condomínios',
                'db_table': 'contatos',
                'ordering': ['-data_inicio', '-id'],
                'managed': False,
            },
        ),
    ]
