# Generated by Django 5.2.17 on 2026-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=150, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True, verbose_name='nome fantasia')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='e-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'administradora',
                'verbose_name_plural': 'administradoras',
                'db_table': 'administradoras',
                'ordering': ['razao_social', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteAdministradora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de encerramento')),
            ],
            options={
                'verbose_name': 'vínculo de administradora',
                'verbose_name_plural': 'histórico de administradoras',
                'db_table': 'cliente_administradora',
                'ordering': ['-data_inicio', '-id'],
                'managed': False,
            },
        ),
    ]
