# Generated by Django 5.2.17 on 2026-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_administradora_clienteadministradora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoAdministradora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contato de administradora',
                'verbose_name_plural': 'contatos de administradoras',
                'db_table': 'contatos_administradora',
                'ordering': ['nome', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsabilidade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(max_length=100, verbose_name='função')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de encerramento')),
            ],
            options={
                'verbose_name': 'responsabilidade',
                'verbose_name_plural': 'responsabilidades',
                'db_table': 'responsabilidades',
                'ordering': ['-data_inicio', '-id'],
                'managed': False,
            },
        ),
    ]
