# Generated by Django 5.2.17 on 2026-09-27 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_encerramento(apps, schema_editor):
    # O SQLite de testes cria as tabelas legadas posteriormente.
    if 'contatos_administradora' in schema_editor.connection.introspection.table_names():
        schema_editor.execute('ALTER TABLE contatos_administradora ADD COLUMN encerrado_em timestamp NULL')


def remover_encerramento(apps, schema_editor):
    if 'contatos_administradora' in schema_editor.connection.introspection.table_names():
        schema_editor.execute('ALTER TABLE contatos_administradora DROP COLUMN encerrado_em')


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_contatoadministradora_responsabilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(criar_encerramento, remover_encerramento)],
            state_operations=[migrations.AddField(model_name='contatoadministradora', name='encerrado_em', field=models.DateTimeField(null=True, blank=True, editable=False))],
        ),
        migrations.CreateModel(
            name='ConfiguracaoDestinatarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administradora', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.administradora')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'configuração de destinatários',
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.CreateModel(
            name='RevisaoDestinatarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('modo', models.CharField(choices=[('usar', 'Usar padrão'), ('complementar', 'Complementar padrão'), ('substituir', 'Substituir padrão')], default='usar', max_length=12)),
                ('motivo', models.CharField(default='Configuração alterada', max_length=80)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='clientes.configuracaodestinatarios')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.clienteadministradora')),
            ],
            options={
                'ordering': ['-numero'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ItemDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encerrado_local', models.BooleanField(default=False)),
                ('boleto', models.BooleanField(default=False)),
                ('nota_fiscal', models.BooleanField(default=False)),
                ('laudo', models.BooleanField(default=False)),
                ('comunicado', models.BooleanField(default=False)),
                ('cobranca', models.BooleanField(default=False)),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.contato')),
                ('contato_administradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.contatoadministradora')),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='clientes.revisaodestinatarios')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='configuracaodestinatarios',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('administradora__isnull', True), ('cliente__isnull', False)), models.Q(('administradora__isnull', False), ('cliente__isnull', True)), _connector='OR'), name='dest_titular_exclusivo'),
        ),
        migrations.AddConstraint(
            model_name='revisaodestinatarios',
            constraint=models.UniqueConstraint(fields=('configuracao', 'numero'), name='dest_revisao_unica'),
        ),
        migrations.AddConstraint(
            model_name='revisaodestinatarios',
            constraint=models.CheckConstraint(condition=models.Q(('modo__in', ['usar', 'complementar', 'substituir'])), name='dest_modo_valido'),
        ),
        migrations.AddConstraint(
            model_name='itemdestinatario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contato__isnull', False), ('contato_administradora__isnull', True)), models.Q(('contato__isnull', True), ('contato_administradora__isnull', False)), _connector='OR'), name='dest_contato_exclusivo'),
        ),
        migrations.AddConstraint(
            model_name='itemdestinatario',
            constraint=models.UniqueConstraint(fields=('revisao', 'contato'), name='dest_direto_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemdestinatario',
            constraint=models.UniqueConstraint(fields=('revisao', 'contato_administradora'), name='dest_empresa_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemdestinatario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encerrado_local', False), models.Q(('boleto', True), ('nota_fiscal', True), ('laudo', True), ('comunicado', True), ('cobranca', True), _connector='OR')), models.Q(('boleto', False), ('cobranca', False), ('comunicado', False), ('contato__isnull', True), ('encerrado_local', True), ('laudo', False), ('nota_fiscal', False)), _connector='OR'), name='dest_categorias_validas'),
        ),
    ]
